<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalManagementSystem.Domain\DentalManagementSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Appointments\Queries\GetAppointmentById\" />
    <Folder Include="Features\Appointments\Command\Create\" />
    <Folder Include="Features\Appointments\Command\Delete\" />
    <Folder Include="Features\Appointments\Command\" />
    <Folder Include="Features\Appointments\Command\SoftDelete\" />
    <Folder Include="Features\Appointments\Command\Update\" />
    <Folder Include="Features\Appointments\Queries\GetAppointmentByPatient\" />
    <Folder Include="Features\Appointments\Queries\GetAppointmentByProcedure\" />
    <Folder Include="Features\Appointments\Queries\GetAppointmentByDate\" />
    <Folder Include="Features\Patients\" />
    <Folder Include="Features\Procedures\Command\Delete\" />
    <Folder Include="Features\Procedures\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

</Project>
