<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3b302d20-1ce0-4548-a831-f2cc4f71735b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Persistence\Appointments\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalManagementSystem.Application\DentalManagementSystem.Application.csproj" />
    <ProjectReference Include="..\DentalManagementSystem.Identity\DentalManagementSystem.Identity.csproj" />
    <ProjectReference Include="..\DentalManagementSystem.Persistence\DentalManagementSystem.Persistence.csproj" />
  </ItemGroup>

</Project>
